/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_5(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	valores  soma_5_arg;
	float  *result_2;
	valores  multiplicacao_5_arg;
	float  *result_3;
	valores  subtracao_5_arg;
	float  *result_4;
	valores  divisao_5_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, calculadora, calc, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	/* ------SOMA --------*/
	printf("\nSOMA\n");
	printf("Digite o valor de A:\n");
	scanf("%f",&soma_5_arg.a);
	printf("Digite o valor de B:\n");
	scanf("%f",&soma_5_arg.b);
	
	result_1 = soma_5(&soma_5_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("O valor da soma eh %f\n",*result_1);	
	}

	/* ------ Multiplicação -----*/
	printf("\nMULTIPLICAÇÃO\n");
	printf("Digite o valor de A:\n");
	scanf("%f",&multiplicacao_5_arg.a);
	printf("Digite o valor de B:\n");
	scanf("%f",&multiplicacao_5_arg.b);

	result_2 = multiplicacao_5(&multiplicacao_5_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("O valor da multiplicação eh %f\n",*result_2);	
	}
	
	/* ------ Subtração -----*/
	printf("\nSUBTRAÇÃO\n");
	printf("Digite o valor de A:\n");
	scanf("%f",&subtracao_5_arg.a);
	printf("Digite o valor de B:\n");
	scanf("%f",&subtracao_5_arg.b);

	result_3 = subtracao_5(&subtracao_5_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("O valor da subtração eh %f\n",*result_3);	
	}

	/* ------ Divisão -----*/
	printf("\nDIVISÃO\n");
	printf("Digite o valor de A:\n");
	scanf("%f",&divisao_5_arg.a);
	printf("Digite o valor de B:\n");
	scanf("%f",&divisao_5_arg.b);

	result_4 = divisao_5(&divisao_5_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("O valor da divisão eh %f\n",*result_4);	
	}



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_5 (host);
exit (0);
}
