/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct valores {
	float a;
	float b;
};
typedef struct valores valores;

#define calculadora 6
#define calc 5

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  float * soma_5(valores *, CLIENT *);
extern  float * soma_5_svc(valores *, struct svc_req *);
#define multiplicacao 2
extern  float * multiplicacao_5(valores *, CLIENT *);
extern  float * multiplicacao_5_svc(valores *, struct svc_req *);
#define subtracao 3
extern  float * subtracao_5(valores *, CLIENT *);
extern  float * subtracao_5_svc(valores *, struct svc_req *);
#define divisao 4
extern  float * divisao_5(valores *, CLIENT *);
extern  float * divisao_5_svc(valores *, struct svc_req *);
extern int calculadora_5_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  float * soma_5();
extern  float * soma_5_svc();
#define multiplicacao 2
extern  float * multiplicacao_5();
extern  float * multiplicacao_5_svc();
#define subtracao 3
extern  float * subtracao_5();
extern  float * subtracao_5_svc();
#define divisao 4
extern  float * divisao_5();
extern  float * divisao_5_svc();
extern int calculadora_5_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_valores (XDR *, valores*);

#else /* K&R C */
extern bool_t xdr_valores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
