/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
soma_5_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("\nSOMA\n");
	printf("O valor de A eh %f\n", argp->a);
	printf("O valor de B eh %f\n", argp->b);
	
	result = argp->a + argp->b;

	printf("\nA soma de A e B eh %f\n", result);

	return &result;
}

float *
multiplicacao_5_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("\nMULTIPLICAÇÃO\n");
	printf("O valor de A eh %f\n", argp->a);
	printf("O valor de B eh %f\n", argp->b);
	
	result = argp->a * argp->b;

	printf("\nA multiplicação de A e B eh %f\n", result);

	return &result;
}

float *
subtracao_5_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("\nSUBTRAÇÃO\n");
	printf("O valor de A eh %f\n", argp->a);
	printf("O valor de B eh %f\n", argp->b);
	
	result = argp->a - argp->b;

	printf("\nA subtração de A e B eh %f\n", result);

	return &result;
}

float *
divisao_5_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("\nDIVISÃO\n");
	printf("O valor de A eh %f\n", argp->a);
	printf("O valor de B eh %f\n", argp->b);
	
	result = argp->a / argp->b;

	printf("\nA divisão de A e B eh %f\n", result);

	return &result;
}
